from setuptools import setup, find_packages

setup(name='irccat3',
      version='0.2',
      description='IRCCat in Python',
      classifiers=["Development Status :: 4 - Beta",
                   "Intended Audience :: Developers",
                   "License :: OSI Approved :: BSD License",
                   "Topic :: Internet :: WWW/HTTP",
                   'Programming Language :: Python',
                   "Programming Language :: Python :: 2",
                   "Programming Language :: Python :: 2.7",
                   "Programming Language :: Python :: 3",
                   "Programming Language :: Python :: 3.3",
                   "Programming Language :: Python :: 3.4",
                   "Programming Language :: Python :: 3.5",
                   ],
      author='Joshua D. Boyd',
      author_email='jdboyd@jdboyd.net',
      license='BSD',
      url='https://github.com/jd-boyd/irccat3',
      packages=find_packages(),
      install_requires=['argparse', 'irc'],
      tests_require=['nose'],
      entry_points={'console_scripts': ['irccat3 = irccat3.main:main',]}
     )
